const ActionTypes = {
    DELETE: 'DELETE',
    PUSH_MATCH_RULE: 'PUSH_MATCH_RULE',
    INPUT: 'INPUT',
    TOGGLE_PREVIEW: 'TOGGLE_PREVIEW',
    MATCH: 'MATCH',
    APPLY: 'APPLY',
    APPLY_FINISH: 'APPLY_FINISH',
    PUSH_MEMORY: 'PUSH_MEMORY'
};

export default ActionTypes;